### ISSUE TITLE
Create Config.cmake files for external dependencies

### ISSUE THREAD

**Issue by jcfr** [Punzo/SlicerAstro#9]
See https://github.com/SBU-BMI/SlicerOpenCV/ for example

**Comment by jcfr** [comment]
See https://github.com/SBU-BMI/SlicerOpenCV/blob/d45866573d35ae300e654da2ceaa829b598c9431/CMakeLists.txt#L53-L69

**Comment by Punzo** [comment]
Hi @jcfr,

I have other two issues:

1) compiling issue on MAC:
for the OpenGL filters
https://github.com/Punzo/SlicerAstro/tree/master/Smoothing/Logic
I use the classes from Steve. I saw this one https://github.com/pieper/CommonGL/pull/2
where should I apply it (I mean the opposite from linux to MAC))? in the CMAKE?

2) redistribution file: 
  I have presets for the volume redering color function stored here:
  https://github.com/Punzo/SlicerAstro/blob/master/AstroVolume/Widgets/Resources/presets.xml
  I noticed that my cmake instructions  
  https://github.com/Punzo/SlicerAstro/blob/master/AstroVolume/Widgets/CMakeLists.txt#L83-L92
  work only locally. When I download the extension from the manager I have not the share folder.
  Do you have hints how I can solve this?

Thanks,

Davide.

**Comment by Punzo** [comment]
@jcfr,

I think I implemented it
https://github.com/Punzo/SlicerAstro/commit/21b4faa91dbc117e293d25600233f71497708115
https://github.com/Punzo/SlicerAstro/commit/407caf162c5234c370debac92b82daee9a449318

however I get following error (I don't get why, because it does not complain for WCSLIB_DIR)

CFITSIO_DIR:/media/Storage/PhD_Groningen/Slicer/SlicerAstro-SuperBuild/cfitsio-install
WCSLIB_DIR:/media/Storage/PhD_Groningen/Slicer/SlicerAstro-SuperBuild/wcslib/lib
CMake Error at /usr/share/cmake-3.5/Modules/CMakePackageConfigHelpers.cmake:258 (message):
  Variable CFITSIO_DIR_CONFIG does not exist
Call Stack (most recent call first):
  CMakeLists.txt:61 (configure_package_config_file)

**Comment by Punzo** [comment]
did it https://github.com/Punzo/SlicerAstro/commit/bc05a20e9a5802c05e842f78a067efcf6b109b04

however it will not fix the issue, because the .so files are still in the Superbuild

**Comment by Punzo** [comment]
solved by https://github.com/Punzo/SlicerAstro/commit/6875923c645dc858d805f6cf56f9b5994279f4b3
